### ISSUE TITLE
Fix Immediate object figures for 32bits and 64bits

### ISSUE THREAD

**Issue by aranega** [SquareBracketAssociates/Booklet-PharoVirtualMachine#3]
Hi all,

The 32bits and 64bits figure for the immediate objects have defects and should be fixed. Unfortunately, I'm under Linux and I cannot modify them as they are omnigraffle drawings.

* __Figure 2-3__ : the drawing of the `SmallInteger` instance should only put in grey the last `1`. The tag for a `SmallInteger` is only `1`, not `01`, meaning that a simple right bit shift is enough to decode it, instead of a two bit shift to the right. I adapted and modify the text in the corresponding sections with PR #2.
* __Figure 2-4__ : change the `SmallInteger` instance description from "63 bits signed int" to "61 bits signed int".

Thanks for the work!

**Comment by Ducasse** [comment]
Thanks vincent.

**Comment by Ducasse** [comment]
We put in grey two bits to show that two bits where reserved. I would prefer to keep it like that because it does not contradict what you are saying. With just one check we can know if we have one smallInteger. is what I'm saying correct?
![Screenshot 2020-05-20 at 09 16 22](https://user-images.githubusercontent.com/432549/82416782-eb254f80-9a7a-11ea-83f4-17869f70ec78.png)

**Comment by Ducasse** [comment]
then you mean Figure 2.5. 
I took the picture from clement and when I read it I do not get why 63 is wrong. 
Because once we know that this is a smallInteger (bit 0 set) all the rest can be used for storing a number, no? so we we can use 63 bits?

![Screenshot 2020-05-20 at 09 21 37](https://user-images.githubusercontent.com/432549/82417091-566f2180-9a7b-11ea-970a-e1ff1e39d320.png)

But you are right since 
SmallInteger maxVal highBit + 1
>> 61

**Comment by aranega** [comment]
Actually, the two bits are reserved only in the case of the pointer to an objet and the character. In the case of a small integer, only one bit is reserved, the `1`, the `0` before could stay in gray, but the value (the `0` itself) should be removed otherwise, it gives the impression that the pattern to tag to exhibit a small integer is `01` whereas it's `1` only. In this case, only 1 bit is enough and it means that every "odd" address is a small integer in 32bit.
I wrote something for that in the pull request #2 to explain it better with an example.

Regarding the 64b immediate, this time, the "tag" is really `001` and not only `1` as in 32b, meaning that we have 61b for encoding the value. I also put an example in the section with the PR #2 :)

**Comment by Ducasse** [comment]
I just fixed the figure and yes this is good to have a code snippet. 
I will change figure 2.3 because it shows something wrong compared to 2.5 or the inverse.

**Comment by aranega** [comment]
Thanks a lot @Ducasse ! If you have time, could you integrate or review the pull request I made? It corrects some stuffs related to the pictures, the immediate value computation and add few details.

**Comment by aranega** [comment]
I just saw the PR merging, Thanks so much @Ducasse !
